// vue/PinCode.vue

<template>
  <div ref="pincodeContainer" :id="id" :class="className"></div>
</template>

<script>
import pinCode from '../pincode';

export default {
  name: "PinCode",
  props: {
    fields: { type: Number, default: 5 },
    placeholder: { type: String, default: "•" },
    autofocus: { type: Boolean, default: true },
    hideinput: { type: Boolean, default: true },
    reset: { type: Boolean, default: false },
    pattern: { type: String, default: "^[0-9]*$" },
    copypaste: { type: Boolean, default: true },
    id: { type: String, default: "pincode-vue" },
    className: { type: String, default: "" }
  },
  mounted() {
    this.initPinCode();
  },
  methods: {
    initPinCode() {
      if (this.$refs.pincodeContainer) {
        this.$refs.pincodeContainer.innerHTML = "";

        new pinCode(this.$refs.pincodeContainer, {
          fields: this.fields,
          placeholder: this.placeholder,
          autofocus: this.autofocus,
          hideinput: this.hideinput,
          reset: this.reset,
          pattern: this.pattern,
          copypaste: this.copypaste,
          complete: (code) => this.$emit('complete', code),
          invalid: (field, index) => this.$emit('invalid', field, index),
          keydown: (e, field, index) => this.$emit('keydown', e, field, index),
          input: (e, field, index) => this.$emit('input', e, field, index),
        });
      }
    }
  },
  watch: {
      fields() { this.initPinCode(); },
      placeholder() { this.initPinCode(); },
      // Re-init on significant prop changes
  }
};
</script>

// react/PinCode.jsx

import React, { useEffect, useRef } from 'react';
import pinCode from '../pincode';

/**
 * React Wrapper for pinCode
 *
 * Usage:
 * <PinCode
 *   fields={5}
 *   onComplete={(code) => console.log(code)}
 * />
 */
const PinCode = ({
  fields = 5,
  placeholder = "•",
  autofocus = true,
  hideinput = true,
  reset = false,
  pattern = "^[0-9]*$",
  copypaste = true,
  onComplete,
  onInvalid,
  onKeydown,
  onInput,
  className = "",
  id = "pincode-container"
}) => {
  const containerRef = useRef(null);
  const instanceRef = useRef(null);

  useEffect(() => {
    if (containerRef.current) {
        // Clear container in case of re-mount issues (though typically strict mode does this)
        containerRef.current.innerHTML = "";

        const options = {
            fields,
            placeholder,
            autofocus,
            hideinput,
            reset,
            pattern,
            copypaste,
            complete: onComplete || (() => {}),
            invalid: onInvalid || (() => {}),
            keydown: onKeydown || (() => {}),
            input: onInput || (() => {})
        };

        instanceRef.current = new pinCode(containerRef.current, options);
    }
  }, [
      fields, placeholder, autofocus, hideinput, reset, pattern, copypaste,
      onComplete, onInvalid, onKeydown, onInput
  ]);

  return (
    <div
        id={id}
        ref={containerRef}
        className={className}
    ></div>
  );
};

export default PinCode;
